---
name: semantic-release

on:
  push:
    branches:
      - '!master'
      - '*'

jobs:
  semantic-release-mock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: semantic-release dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: cycjimmy/semantic-release-action@v2.7.0
        with:
          dry_run: true
          branches: |
            [
              "${{ env.GITHUB_BASE_REF }}"
            ]
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
